Add new functions to OpalGraphics
gnustep/libs-opal pull request #4
Opened 2017-07-20 02:37 UTC by theiostream

This pull requests adds new functions to OpalGraphics or fixes existing ones, almost 90% on CGPath.

2017-07-20 06:34 UTC, fredkiefer requested changes
I think most of this is great and all of it a big improvement over the previous implementation. If you don't want to clean up the things I commented on this is also fine for me, but you should add some comments to the code or in the case of the bounding box, call the old version instead.

2017-07-20 06:34 UTC, fredkiefer commented on Source/OpalGraphics/CGPath.m
> +	  case kCGPathElementAddCurveToPoint:
Here we are missing the case of kCGPathElementAddQuadCurveToPoint which does not exist for NSBezierPath.

2017-07-20 06:34 UTC, fredkiefer commented on Source/OpalGraphics/CGPath.m
> +  NSPoint center = NSMakePoint(x, y);
As I already wrote I would prefer the CGPoint version here.

2017-07-20 06:34 UTC, fredkiefer commented on Source/OpalGraphics/CGPath.m
> +  if (l <= 0)
Shpuld we use a shared bit of logic between this function and CGPathAddArc when to lineTo, moveTo or do nothing? Both current versions look suboptimal.
I have to admit, I did not look at the full version of the function and may be totally off here. What I am think of is that when ever we start an arc we first must decide how to get to the first point of it. And this should be properly implemented.

2017-07-20 06:34 UTC, fredkiefer commented on Source/OpalGraphics/CGPath.m
> +CGRect CGPathGetPathBoundingBox(CGPathRef path)
My computer graphics lectures were a long time ago but from what I remember your algorithm seems completely wrong. What you do is compute the bounding box of the curve by leaving out some of the control points. This won't give you the actual bounds of the curve. Please have a look at http://floris.briolas.nl/floris/2009/10/bounding-box-of-cubic-bezier/ or other explanations on the web.
What you basically have to do for the arc bits is to compute enough points on the curve to determine an exact bounding box.

2017-07-21 19:12 UTC, theiostream commented on Source/OpalGraphics/CGPath.m
> +	  case kCGPathElementAddCurveToPoint:
I'm not sure on how to implement the winding algorithm for quadratic curves; for now I left it as a `FIXME`. Could you point me in any direction?

2017-07-21 19:12 UTC, theiostream commented on Source/OpalGraphics/CGPath.m
> +  NSPoint center = NSMakePoint(x, y);
Fixed.

2017-07-21 19:12 UTC, theiostream commented on Source/OpalGraphics/CGPath.m
> +CGRect CGPathGetPathBoundingBox(CGPathRef path)
Fixed.

2017-07-21 19:14 UTC, theiostream commented on Source/OpalGraphics/CGPath.m
> +  if (l <= 0)
I agree with your concern; if you think both current versions are suboptimal though, could you suggest a "reference" version so I can reimplement both and keep it uniform?

2017-07-21 22:02 UTC, fredkiefer commented on Source/OpalGraphics/CGPath.m
> +  if (l <= 0)
Sorry, I had another look at your current code and the decision in CGPathAddArc now looks correct to me. And the logic in ArcToPoint has to be different. Forget this whole comment, I should have looked at the code of the whole file not just the changes.

2017-07-21 22:04 UTC, fredkiefer approved these changes
With the last changes I think this code is ready for a merge. There are still a few missing bits, but these might be added later.

2017-07-23 23:19 UTC, ivucica requested changes
I will merge once the `wtf` is gone 👍

2017-07-23 23:19 UTC, ivucica commented on Tests/paths.m
> +  NSLog(@"wtf %@", NSStringFromRect(CGPathGetBoundingBox(quadCurve)));
Please remove/replace the `wtf` :)

2017-07-25 01:48 UTC, theiostream commented
Removed the `wtf`. Sorry for that.

2017-07-25 21:50 UTC, ivucica approved these changes

2017-07-25 21:50 UTC, merged